# ===============================
# SERVER CONFIG
# ===============================
server.port=8082

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=your-256-bit-secret-your-256-bit-secret

# ===============================
# LOGGING CONFIG
# ===============================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.multitenant.saas=DEBUG

# ===============================
# OPTIONAL (DEV DEBUGGING)
# ===============================
# Uncomment if needed
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connectionTimeout=60000
spring.datasource.hikari.validationTimeout=3000

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
